### PR TITLE
fix(js-runtime): make Headers class case insensitive

### LINKED ISSUE #226: Headers API doesn't ignore case
**Describe the bug**
`Headers` API should ignore letter cases but it doesn't. It causes many failures in Rakkas's integration tests.

**To Reproduce**
Run the following snippet:

```js
const headers = new Headers();
headers.append("X-Test", "1234");
console.log("HEADERS", Object.fromEntries(headers.entries()));
console.log(headers.get("X-Test")); // Prints 1234
console.log(headers.get("x-test")); // Prints undefined
```

**Expected behavior**
I expect `headers.get("x-test")` to be equal to `headers.get("X-Test")`.

**Information:**
 - OS: Linux Mint
 - Browser: Doesn't apply
 - Version: 0.3.3

### PR DESCRIPTION
**Pull request by cyco130**
## About

This PR makes the `Headers` class case insensitive, as required by the spec. Tests have been modified to cover case insensitivity. Fixes #226.

### CODE REVIEW

File: packages/js-runtime/src/runtime/fetch.ts [hunk 1]
```diff
@@ -8,17 +8,18 @@ export class Headers {
     if (init) {
       if (Array.isArray(init)) {
         init.forEach(([key, value]) => {
-          this.addValue(key, value);
+          this.addValue(key.toLowerCase(), value);
         });
       } else {
         Object.entries(init).forEach(([key, value]) => {
-          this.addValue(key, value);
+          this.addValue(key.toLowerCase(), value);
```
Comment (QuiiBz) [inline packages/js-runtime/src/runtime/fetch.ts:15]: We can revert both of these lines, since we already call `toLowerCase()` inside `addValue()`

File: packages/js-runtime/src/__tests__/fetch.test.ts [hunk 2]
```diff
@@ -122,20 +122,20 @@ describe('Headers', () => {
...
         a: 'b',
-        c: 'd',
+        C: 'd',
       });
       headers.set('a', 'e');
       headers.set('c', 'f');
       expect(headers.get('a')).toEqual('e');
-      expect(headers.get('c')).toEqual('f');
+      expect(headers.get('C')).toEqual('f');
     });
```
Comment (QuiiBz) [inline packages/js-runtime/src/__tests__/fetch.test.ts:139]: Could you add another test for `set()`, by setting a new header with the key in uppercase and verifying if the key has been converted to lowercase?

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks for the PR! Two small suggestions:

File: packages/js-runtime/src/runtime/fetch.ts (hunk 1 above)
Comment (cyco130) [reply packages/js-runtime/src/runtime/fetch.ts]: Of course, d'oh!

File: packages/js-runtime/src/__tests__/fetch.test.ts (hunk 2 above)
Comment (cyco130) [reply packages/js-runtime/src/__tests__/fetch.test.ts:141]: Done.

**Review by QuiiBz — APPROVED** [review]
LGTM, thanks! (I pushed [c155054](https://github.com/lagonapp/lagon/pull/227/commits/c1550545337d09c7dc8ee96b6a54d37ebcd0eeb9) to update a test in the Rust runtime)
